# Generated by Django 3.1 on 2020-09-02 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200902_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubedata',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='map.place'),
        ),
    ]
