# Generated by Django 3.1 on 2020-09-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200902_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seoul_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.place')),
            ],
        ),
    ]
