# Generated by Django 3.1 on 2020-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_tourreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='trip_url',
            field=models.URLField(blank=True),
        ),
    ]
