# Generated by Django 3.1 on 2020-10-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_place_trip_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourreview',
            name='info_title',
            field=models.TextField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
