# Generated by Django 3.1 on 2020-11-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_tourreview_info_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='visit_date',
            field=models.CharField(max_length=20),
        ),
    ]
