# Generated by Django 3.1 on 2020-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20201125_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='info',
            field=models.TextField(max_length=1250),
        ),
        migrations.AlterField(
            model_name='tourreview',
            name='info_title',
            field=models.TextField(max_length=200),
        ),
    ]
