# Generated by Django 3.1 on 2020-12-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20201125_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='info',
            field=models.TextField(max_length=2500),
        ),
    ]
