# Generated by Django 3.1 on 2020-12-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20201229_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
